---
- name: Require 2.X version of Ansible
  assert:
    that: ansible_version.major >= 2

- name: Require monitor_host to be defined
  fail:
    msg: "monitor_host must be defined"
  when: monitor_host is not defined

- name: Test for supported distribution
  assert:
    that: >
      ansible_os_family == "RedHat" or
      ansible_os_family == "Debian"

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

# Super cool include that can be as specific as you need it to be
- name: OS specific prep
  include: "{{ item }}"
  with_first_found:
    - files:
        - installs/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml
        - installs/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml
        - installs/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml
        - installs/{{ ansible_distribution }}.yml
        - installs/{{ ansible_os_family }}.yml
      skip: true

- name: Install carbon packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ carbon_pkgs }}"
  notify:
    - Restart Carbon services
  tags:
    - carbon_pkg

- debug: var=monitor_host

- name: Configure carbon configuration
  template:
    src: carbon.conf.j2
    dest: "{{ carbon_config_path }}"
    force: yes
  notify:
    - Restart Carbon services
  tags:
    - carbon_config

- name: Make Carbon service running
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ carbon_services }}"
