---
- name: Require 2.X version of Ansible
  assert:
    that: ansible_version.major >= 2

- name: Test for supported distribution
  assert:
    that: >
      ansible_os_family == "RedHat" or
      ansible_os_family == "Debian"

# 2.0 will give you a false depreciation warning
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: OS specific prep
  include: installs/{{ ansible_os_family }}.yml
  static: false

- name: Install Collectd package and extras
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ collectd_pkgs }}"
  notify:
    - Restart collectd service
  tags:
    - collectd_pkg

- name: Configure CollectD
  template:
    src: collectd.conf.j2
    dest: "{{ collectd_config_path }}"
    force: yes
  notify:
    - Restart collectd service
  tags:
    - collectd_config

- name: Make sure collectd service is enabled and running
  service:
    name: collectd
    enabled: yes
    state: started
