---
- name: Add collectd backports keyring for RedHat
  rpm_key:
    key: http://pkg.ci.collectd.org/pubkey.asc
    state: present

- name: Add collectd backports repository for RedHat
  yum_repository:
    name: collectd
    description: "collectd repo"
    baseurl: "https://pkg.ci.collectd.org/rpm/collectd-5.5/epel-{{ ansible_lsb.major_release }}-{{ ansible_architecture }}/"
    state: present
