---

# Package to be installed (you can force a specific version here)
collectd_redhat_pkgs:
  - collectd
  - collectd-virt
  - collectd-ceph
collectd_ubuntu_pkgs:
  - collectd

collectd_redhat_config_path: "/etc/collectd.conf"
collectd_ubuntu_config_path: "/etc/collectd/collectd.conf"
